services:
  mysql:
    image: mysql
    container_name: mysql-lsim
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - lsim-network

  server-lsim:
    extends:
      file: ./server-lsim/docker-compose.yml
      service: server-lsim

  pagamentos-lsim:
    extends:
      file: ./pagamentos-lsim/docker-compose.yml
      service: pagamentos-lsim

  pedidos-lsim:
    extends:
      file: ./pedidos-lsim/docker-compose.yml
      service: pedidos-lsim

  gateway-lsim:
    extends:
      file: ./gateway-lsim/docker-compose.yml
      service: gateway-lsim

networks:
  lsim-network:
    driver: bridge