services:

  mysql:
    image: mysql
    container_name: mysql-lsim
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - lsim-network

  server-lsim:
    image: server-lsim
    container_name: server-lsim
    build:
      context: ./server-lsim
    ports:
      - "8761:8761"
    networks:
      - lsim-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-lsim:
    image: gateway-lsim
    container_name: gateway-lsim
    build:
      context: ./gateway-lsim
    ports:
      - "8762:8762"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
    environment:
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/
  
  pagamentos-lsim:
    image: pagamentos-lsim
    container_name: pagamentos-lsim
    build:
      context: ./pagamentos-lsim
    ports:
      - "8080"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
    environment:
      - DB_HOST=mysql-lsim
      - DB_PORT=3306
      - DB_NAME=lsimfood-pagamento
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - SERVER_PORT=0
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/

  pedidos-lsim:
    image: pedidos-lsim
    container_name: pedidos-lsim
    build:
      context: ./pedidos-lsim
    ports:
      - "8080"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
    environment:
      - DB_HOST=mysql-lsim
      - DB_PORT=3306
      - DB_NAME=lsimfood-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - SERVER_PORT=0
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/

networks:
  lsim-network:
    driver: bridge