services:
  mysql:
    image: mysql
    container_name: mysql-lsim
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - lsim-network
  
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    networks:
      - lsim-network
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/dados:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=lsim
        - RABBITMQ_DEFAULT_PASS=lsim

  server-lsim:
    container_name: server-lsim
    build:
      context: ./server-lsim
    ports:
      - "8761:8761"
    networks:
      - lsim-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-lsim:
    container_name: gateway-lsim
    build:
      context: ./gateway-lsim
    ports:
      - "8762:8762"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
    environment:
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/
  
  pagamentos-lsim:
    build:
      context: ./pagamentos-lsim
    # ports:
    #   - "8080"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
      - rabbitmq
    environment:
      - DB_HOST=mysql-lsim
      - DB_PORT=3306
      - DB_NAME=lsimfood-pagamento
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - SERVER_PORT=0
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=lsim
      - RABBITMQ_PASSWORD=lsim

  pedidos-lsim:
    build:
      context: ./pedidos-lsim
    # ports:
    #   - "8080"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
      - rabbitmq
    environment:
      - DB_HOST=mysql-lsim
      - DB_PORT=3306
      - DB_NAME=lsimfood-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=mysql
      - SERVER_PORT=0
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=lsim
      - RABBITMQ_PASSWORD=lsim

  avaliacao-lsim:
    build:
      context: ./avaliacao-lsim
    # ports:
    #   - "8080"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
      - rabbitmq
    environment:
      - SERVER_PORT=0
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=lsim
      - RABBITMQ_PASSWORD=lsim

networks:
  lsim-network: